### ISSUE TITLE
Cannot open tau3mu_mixed.pkl

### ISSUE THREAD

**Issue by WtaoZhao** [Graph-COM/LRI#1]
Hi, after downloading tau3mu_mixed.pkl, I came across this error when trying to open it. Specifically, at this line of code,
df = pd.read_pickle(self.raw_dir + '/tau3mu_mixed.pkl'), the following error was reported:
AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/home/zhaowentao/anaconda3/envs/torch2/lib/python3.8/site-packages/pandas/_libs/internals.cpython-38-x86_64-linux-gnu.so'>
My pandas version is 1.3.5, the same as the one specified in requirements.txt. I also tried to load it directly using pickle.load(), but the same error occured. Since I need to modify the process(self) function to add some attributes to Data object, I have to download raw file and process it by myself instead of using the processed file provided (However, I was able to download the processed file and open it). Can you help me with this error? Many thanks.

**Comment by siqim** [comment]
Hi @WtaoZhao,

I just tested with pandas 1.4.1, and it works well. Can you upgrade the pandas and try it again?

-siqi

**Comment by WtaoZhao** [comment]
It works after upgrading pandas. Thank you for your help!
